global:
  name: consul
  datacenter: dc1
  image: "hashicorp/consul:1.15.4"

server:
  replicas: 1
  bootstrapExpect: 1

ui:
  enabled: true

connectInject:
  enabled: true
  namespaceSelector:
    matchLabels:
      consul-injection: enabled

controller:
  enabled: true

client:
  enabled: true
